version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: author-newsletter-db
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secretpassword}
      - POSTGRES_DB=${DB_NAME:-author-newsletter}
    hostname: localhost
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "${APP_PORT:-8080}:8080"
    container_name: author-newsletter-api
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
